package com.example.app.models

import kotlinx.serialization.Serializable

@Serializable
data class ApplicationDataDto(
    /** draft application data */
    val selectedType: String? = null,
    val selectedUniversity: String? = null,

    /** submitted application data */
    val firstName: String? = null,
    val secondName: String? = null,
    val lastName: String? = null,
    val email: String? = null,
    val phoneNumber: String? = null,
    val photo: String? = null,
    val passport_typeOfPassport_id: String? = null,
    val passport_birthPlace: String? = null,
    val passport_series: String? = null,
    val passport_number: String? = null,
    val passport_issuedBy: String? = null,
    val passport_dateIssued: String? = null,
    val passport_unzdr: String? = null,
    val passport_validity: String? = null,
    val dateBirth: String? = null,
    val typeOfGenderOfPerson_id: String? = null,
    val passportPhoto1: String? = null,
    val passportPhoto2: String? = null,
    val passportPhoto3: String? = null,
    val selectedQualification: String? = null,
    val course: String? = null,
    val faculty_id: String? = null,
    val specialization_id: String? = null,
    val financialSource_id: String? = null,
    val formOfEducation_id: String? = null,
    val address_region: String? = null,
    val address_district: String? = null,
    val address_typeOfCity_id: String? = null,
    val address_city: String? = null,
    val address_typeOfStreet_id: String? = null,
    val address_street: String? = null,
    val address_house: String? = null,
    val address_apartment: String? = null,
    val residence_region: String? = null,
    val residence_district: String? = null,
    val residence_typeOfCity_id: String? = null,
    val residence_city: String? = null,
    val residence_typeOfStreet_id: String? = null,
    val residence_street: String? = null,
    val residence_house: String? = null,
    val residence_apartment: String? = null,
    val residenceAddressDifferent: String? = null,
    val familyMembersData: String? = null,
    val familyPhoto: String? = null,
    val privilegeExists: String? = null,
    val privilege_typeOfPrivilege_id: String? = null,
    val privilege_otherPrivilege: String? = null,
    val privilegePhoto1: String? = null,
    val privilegePhoto2: String? = null,
    val privilegePhoto3: String? = null,
    val fluorography_lastDate: String? = null,
    val fluorographyPhoto1: String? = null,
    val fluorographyPhoto2: String? = null,
    val medicalVaccinePhoto: String? = null,
    val appealToAdministration: String? = null,
    val selectedDormitory: String? = null,
    val selectedRoom: String? = null,
    val consent: String? = null,
)
